import re
from copy import deepcopy
import pytest


class TM4JReporter:
    def __init__(self):
        # should be read from pytest.ini and use <prj_key>-T instead of T
        self.prefix = 'T'

    @staticmethod
    def _resolve_outcome(outcome: str) -> str:
        """
        Map pytest test outcome to tm4j outcome
        """
        # A key is for pytest, value is for TM4J
        outcomes = {
            'passed': 'Pass',
            'failed': 'Fail'}
        return outcomes[outcome]

    def prepare_tm4j_report_json(self, pytest_json: dict) -> dict:
        """
        Prepares the data for report
        Example output:

        {'T303': {'name': 'one', 'outcome': 'Pass',
                  'steps': ['test one step A', 'test one step B'],
                  'summary': 'test one summary'},
         'T304': {'name': 'two', 'outcome': 'Pass',
                  'steps': ['test two step A', 'test two step B'],
                  'summary': 'test two summary'}}

        :type pytest_json: dict generated by the json-report plugin
        """
        report = pytest_json
        results = {}
        tests_wo_tm4j_id = []

        for test_dict in report['tests']:
            test_name_full = test_dict['nodeid']
            # test_common.py::test_T303_one
            test_name_wo_module = test_name_full.split('::')[-1]
            # test_T303_one

            tm4j_num_ptrn = f'{self.prefix}\d+'
            t_name_ptrn = '.*'
            is_test_valid_tm4j = re.match(
                f'^.*_({tm4j_num_ptrn})_({t_name_ptrn})', test_name_wo_module)
            if not is_test_valid_tm4j:
                tests_wo_tm4j_id.append(test_name_full)
                continue
            tm4j_num = is_test_valid_tm4j.group(1)
            test_name = is_test_valid_tm4j.group(2)

            results[tm4j_num] = {
                'name': test_name,
                'outcome': self._resolve_outcome(test_dict['outcome'])}
            results[tm4j_num].update(test_dict['metadata'])

        if tests_wo_tm4j_id:
            print(f"\n\nWARNING: some test results cannot be exported to TM4J "
                  f"because they don't have a TM4J test ID in their name."
                  f"\nexample: \"test_{self.prefix}123_testname\" "
                  f"where {self.prefix}123 is a TM4J test ID"
                  f"\ntests affected: {' '.join(tests_wo_tm4j_id)}")

        return results


def pytest_json_modifyreport(json_report: dict):
    """
    The hook belongs to json-report plugin
    Rewrites an original report
    """
    json_report_orig = deepcopy(json_report)
    for key in json_report_orig.keys():
        del json_report[key]
    t = TM4JReporter()
    json_report['tests'] = t.prepare_tm4j_report_json(json_report_orig)


def pytest_json_runtest_metadata(item, call) -> dict:
    """
    The hook belongs to json-report plugin
    Reads the metadata from the test body and writes it to the report
    """
    if call.when == 'teardown':
        result = {'steps': item.meta_steps, 'summary': item.meta_summary}
        return result


@pytest.fixture
def tm4j_r(request):
    """
    TM4J-related metadata can be added to test using MetaHolder class

    def test_T303_one(tm4j_r):
        tm4j_r.summary = 'test one summary'
        tm4j_r.step('test one step A')
        tm4j_r.step('test one step B')
    """
    class MetaHolder:
        def __init__(self):
            self.steps = []
            self.summary = None

        def step(self, text: str):
            self.steps.append(text)

    m = MetaHolder()
    yield m
    request.node.meta_steps = m.steps
    request.node.meta_summary = m.summary
    return m
